# Stage script: Stream heavy markdown content token-by-token
# Tests streaming rendering with rich markdown formatting

(import core/stage :as stage)

(def content
  (string
    "# Comprehensive Analysis Report\n\n"
    "## Executive Summary\n\n"
    "This report contains **critical findings** that require *immediate attention*. "
    "The data shows a `significant correlation` between variables.\n\n"
    "## Key Metrics\n\n"
    "| Metric | Value | Delta |\n"
    "|--------|-------|-------|\n"
    "| Throughput | 1,234 req/s | +15% |\n"
    "| Latency p50 | 12ms | -8% |\n"
    "| Latency p99 | 89ms | -22% |\n"
    "| Error rate | 0.02% | -50% |\n\n"
    "## Implementation Details\n\n"
    "The core algorithm uses a **divide-and-conquer** approach:\n\n"
    "```rust\n"
    "fn merge_sort<T: Ord>(mut arr: Vec<T>) -> Vec<T> {\n"
    "    let len = arr.len();\n"
    "    if len <= 1 {\n"
    "        return arr;\n"
    "    }\n"
    "    let mid = len / 2;\n"
    "    let right = arr.split_off(mid);\n"
    "    let left = merge_sort(arr);\n"
    "    let right = merge_sort(right);\n"
    "    merge(left, right)\n"
    "}\n\n"
    "fn merge<T: Ord>(left: Vec<T>, right: Vec<T>) -> Vec<T> {\n"
    "    let mut result = Vec::with_capacity(left.len() + right.len());\n"
    "    let (mut i, mut j) = (0, 0);\n"
    "    while i < left.len() && j < right.len() {\n"
    "        if left[i] <= right[j] {\n"
    "            result.push(left[i]);\n"
    "            i += 1;\n"
    "        } else {\n"
    "            result.push(right[j]);\n"
    "            j += 1;\n"
    "        }\n"
    "    }\n"
    "    result.extend_from_slice(&left[i..]);\n"
    "    result.extend_from_slice(&right[j..]);\n"
    "    result\n"
    "}\n"
    "```\n\n"
    "### Performance Characteristics\n\n"
    "1. **Time complexity**: O(n log n) in all cases\n"
    "2. **Space complexity**: O(n) auxiliary space\n"
    "3. **Stability**: Yes, maintains relative order\n"
    "4. **Adaptivity**: No, doesn't benefit from pre-sorted data\n\n"
    "## Secondary Analysis\n\n"
    "The following observations were made during testing:\n\n"
    "- The system handles **concurrent requests** gracefully under load\n"
    "- Memory usage remains *stable* even with 10,000+ connections\n"
    "- The `connection pool` automatically scales based on demand\n"
    "- Error recovery follows an **exponential backoff** strategy\n\n"
    "```python\n"
    "import asyncio\n"
    "from typing import List, Optional\n\n"
    "class ConnectionPool:\n"
    "    def __init__(self, max_size: int = 100):\n"
    "        self.max_size = max_size\n"
    "        self.pool: List[Connection] = []\n"
    "        self.semaphore = asyncio.Semaphore(max_size)\n\n"
    "    async def acquire(self) -> Connection:\n"
    "        await self.semaphore.acquire()\n"
    "        if self.pool:\n"
    "            return self.pool.pop()\n"
    "        return await Connection.create()\n\n"
    "    async def release(self, conn: Connection):\n"
    "        if len(self.pool) < self.max_size:\n"
    "            self.pool.append(conn)\n"
    "        else:\n"
    "            await conn.close()\n"
    "        self.semaphore.release()\n"
    "```\n\n"
    "## Conclusion\n\n"
    "The results demonstrate that the optimized implementation achieves:\n\n"
    "- **83% reduction** in average frame render time\n"
    "- **>60fps** effective scroll performance\n"
    "- **89% reduction** in streaming frame overhead\n"
    "- Near-zero diff cost on clean frames\n\n"
    "Further optimization should focus on reducing visual row computation cost "
    "and improving markdown parsing throughput for large documents.\n"))

(stage/respond (stage/text-stream content :token-delay 0.002))
